platform:
  security:
    jwt:
      issuer: kidzSchool
      expiration: 30 #minutes
      secretKey: your256bitsecretkeyyour256bitsecretkey
    confirmation-token:
      expiration: 60 #minutes

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kidz_school
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: kkidzschoolproject@gmail.com
    password: rgxhgiueaxofxryt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  liquibase:
    change-log: classpath:/liquibase/changelog.xml

site:
  url: http://localhost:8080

springdoc:
  packages-to-scan: com.example.kidz_school.controller
