spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kidz_school
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: kkidzschoolproject@gmail.com
    password: rgxhgiueaxofxryt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

